const drinks = [
  {
    id: 1,
    name: "Kapućino",
    description: "Sa mlekom",
    price: 4.2,
    category: "Kafe",
    image: "kafa.png",
  },
  {
    id: 2,
    name: "Espresso",
    description: "Jak i aromatičan",
    price: 3.5,
    category: "Kafe",
    image: "kafa.png",
  },
  {
    id: 3,
    name: "Coca-Cola",
    description: "Osvežavajuće piće",
    price: 2.0,
    category: "Bezalkoholno",
    image: "kafa.png",
  },
  {
    id: 4,
    name: "Fanta",
    description: "Sa ukusom narandže",
    price: 2.0,
    category: "Bezalkoholno",
    image: "kafa.png",
  },
  {
    id: 5,
    name: "Heineken",
    description: "Lager pivo",
    price: 3.5,
    category: "Piva",
    image: "kafa.png",
  },
  {
    id: 6,
    name: "Guinness",
    description: "Crno pivo",
    price: 4.5,
    category: "Piva",
    image: "kafa.png",
  },
  {
    id: 7,
    name: "Vino Merlot",
    description: "Crveno vino",
    price: 6.0,
    category: "Alkoholno",
    image: "kafa.png",
  },
  {
    id: 8,
    name: "Rakija",
    description: "Šljivovica",
    price: 4.0,
    category: "Alkoholno",
    image: "kafa.png",
  },
  {
    id: 9,
    name: "Turska kafa",
    description: "Domaća",
    price: 2.1,
    category: "Kafe",
    image: "kafa.png",
  },
  {
    id: 10,
    name: "Ness kafa",
    description: "Nema opisa",
    price: 2.5,
    category: "Kafe",
    image: "kafa.png",
  },
];

export default drinks;
